#!/bin/bash
SQSRecords='{"Records": []}'

SQSRecord='{
		"messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
		"receiptHandle": "MessageReceiptHandle",
		"body": "Hello from SQS!",
		"attributes": {
			"ApproximateReceiveCount": "1",
			"SentTimestamp": "1523232000000",
			"SenderId": "123456789012",
			"ApproximateFirstReceiveTimestamp": "1523232000001"
		},		
		"messageAttributes": {
			"data": {
				"binaryValue": "REPLACE",
				"dataType": "binary"
			}
		},
		"md5OfBody": "7b270e59b47ff90a553787216d55d91d",
		"eventSource": "aws:sqs",
		"eventSourceARN": "arn:aws:sqs:us-east-1:123456789012:MyQueue",
		"awsRegion": "us-east-1"
}'

for var in "$@"
do
	data=$(cat testEvents.json | jq ".$var" | base64)
	record=$(echo $SQSRecord | jq '.messageAttributes.data.binaryValue = "'"$data"'"')
	SQSRecords=$(echo $SQSRecords | jq ".Records[.Records| length] |= . + $record")
done

docker run --rm -v $PWD:/var/task --env-file dev.env lambci/lambda:go1.x main "$SQSRecords"